### PR TITLE
Fix error reporting bugs

### LINKED ISSUE #153: Not prompt error message when connect site failed
### Environments

- OS: Windows 10/OS 10.15.3
- VS Code version: 1.48.0
- Extension version: 0.5.0

### To Reproduce

1. Set default groupId and artifactId and service URL(eg: http://localhost:8080) 
2. Open Command Palette, execute the command `Spring Initializr: Generate a Maven Project`
3. press <Enter> to use default groupId and artifactId

### Current behavior
Not prompt error message when connect site failed, only show error in toggle developer tools
image

### Expect behavior
image

### PR DESCRIPTION
**Pull request by CsCherrYY**
Fix #153 and error reporting in other steps

### CODE REVIEW

**Review by Eskibear — APPROVED** [review]

File: src/handler/utils.ts [hunk 1]
```diff
@@ -125,10 +133,15 @@ export async function createInputBox(inputMetaData: IInputMetaData): Promise<boo
...
+                return resolve(true);
             }),
             inputBox.onDidHide(() => {
-                reject();
+                if (inputMetaData.pickStep instanceof SpecifyGroupIdStep) {
+                    return reject(new OperationCanceledError("GroupId not specified."));
+                } else if (inputMetaData.pickStep instanceof SpecifyArtifactIdStep) {
+                    return reject(new OperationCanceledError("ArtifactId not specified."));
+                }
+                return reject();
```
Comment (Eskibear) [inline src/handler/utils.ts:144]: why `reject()` without `reason`?

**Review by Eskibear — CHANGES_REQUESTED** [review]

**Review by Eskibear — APPROVED** [review]
