### PR TITLE
Fix semicolon in title bug

### LINKED ISSUE #158: Rollback field have a semicolon  " ; "
**Environments**

- OS: Windows 10/OS 10.15.3
- VS Code version: 1.49.2
- Extension version: 0.5.0

**To Reproduce**

1. Open Command Palette, execute the command Spring Initializr: Generate a Maven Project
2. Select a spring boot version
3. Go to project language, observe rollback field have a semicolon " **;** "

**Current behavior**
image

**Expect behavior**
Rollback field shouldn't have a  a semicolon " **;** "

### PR DESCRIPTION
**Pull request by CsCherrYY**
Fix #158

### CODE REVIEW

File: src/handler/SpecifyDependenciesStep.ts [hunk 1]
```diff
@@ -38,6 +38,7 @@ export class SpecifyDependenciesStep implements IStep {
             const quickPickItems: Array<QuickPickItem & IDependenciesItem> = await dependencyManager.getQuickPickItems(projectMetadata.serviceUrl, projectMetadata.bootVersion, { hasLastSelected: true });
             result = await new Promise<boolean>(async (resolve, reject) => {
                 const pickBox: QuickPick<QuickPickItem & IDependenciesItem> = window.createQuickPick<QuickPickItem & IDependenciesItem>();
+                pickBox.title = "Spring Initializr: Search for dependencies",
```
Comment (Eskibear) [inline src/handler/SpecifyDependenciesStep.ts:41]: Choose dependencies

**Review by Eskibear — COMMENTED** [review]
Thanks.
LGTM, but with some wording suggestions.

**Review by Eskibear — APPROVED** [review]
